# Sam setting
sam_checkpoint: ./checkpoints/sam_vit_h_4b8939.pth
model_type: vit_h
device: cuda
res_embed: 64
res_sam: 1024
threshold_cos_sim: 0.5

# grounding-dino setting
grounding_dino_config: "/home/wpals113/mmdetection/configs/mm_grounding_dino/grounding_dino_swin-l_pretrain_all.py"
grounding_dino_checkpoint: ./checkpoints/grounding_dino_swin-l_pretrain_all-56d69e78.pth
grounding_dino_texts: "building."
grounding_dino_pred_score_thr: 0.1
grounding_dino_iou_thr: 0.35
grounding_dino_save_dir: ./workspace/object_detection/outputs

image_dir_base: ./data/processed
output_dir_base: ./workspace/outputs
