initial_tif_path: ./data/raw_data/K3A_20151028.tif
new_tif_path: ./data/raw_data/K3A_20231006.tif
output_dir_base: ./data/processed
basic_res: 512
times: [2, 3, 4]
step: 4
original_shape: [3200, 3200]

# final result
final_result_dir: ./outputs
pred_thr: 0.15